name: CI-Composer-Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - 'release/**'
      - 'feature/**'
      - 'main'

jobs:
  composer-validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php-versions: [ '7.4','8.0','8.1','8.2' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      id: setup-php
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl, curl

    - name: Print PHP version
      run: echo ${{ steps.setup-php.outputs.php-version }}

    - name: Validate composer.json
      run: composer validate